apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube

apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secret
  namespace: sonarqube
type: Opaque
data:
  jdbc-password: "${jdbc-password}"
  password: "${password}"
  currentPassword: "${password}"