apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secret
  namespace: sonarqube
type: Opaque
data:
  jdbc-password: "${extra_vars.sonarqube_jdbc_password}"
  password: "${extra_vars.sonarqube_password}"
  currentPassword: "${extra_vars.sonarqube_password}"
