- name: Create htpasswd file for authentication
  become: yes
  command:
    cmd: htpasswd -b -c /etc/nginx/.htpasswd {{ atlantis_user }} {{ atlantis_password }}
  changed_when: false
  tags:
    - configure_nginx
    - create_htpasswd

- name: Generate Let's Encrypt certificate using Nginx
  become: yes
  command: certbot --nginx -d {{ atlantis_domain }} --non-interactive --agree-tos -m imamariefrahmann@gmail.com
  tags:
    - configure_nginx
    - generate_letsencrypt_certificate

- name: Copy Nginx Configuration for Atlantis
  become: yes
  template:
    src: nginx-atlantis-ssl.conf.j2
    dest: /etc/nginx/sites-available/atlantis
  tags:
    - configure_nginx
    - copy_nginx_configuration
